services:
  lgetn-event:
    build: .
    container_name: lgetn-10m-ceremony
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
